### ISSUE TITLE
Graph::QL::Resolvers::* or Graph::QL::Resolver::*?

### ISSUE THREAD

**Issue by stevan** [stevan/p5-Graph-QL#25]
Currently it is plural (`Resolvers`) and the items within are singular (`FieldResolver`, etc) which is not that offensive to me, but it does make me twitch a little.

**Comment by gonzus** [comment]
It seems plurals are already everywhere:
```
$ find lib/ -type f | egrep 's\.pm$'
lib//Graph/QL/Resolvers.pm
lib//Graph/QL/Util/Errors.pm
lib//Graph/QL/Util/Decorators.pm
lib//Graph/QL/Util/Strings.pm
lib//Graph/QL/Util/Schemas.pm
lib//Graph/QL/Util/Assertions.pm
lib//Graph/QL/Schema/BuiltIn/Directives.pm
lib//Graph/QL/Schema/BuiltIn/Scalars.pm
lib//Graph/QL/Introspection/Resolvers.pm
```

**Comment by stevan** [comment]
So yes, I should explain this in more detail perhaps. Note, I am going to skip the `Introspection` namespace, that whole thing needs an overhaul.

Here is my thinking of where plurals are okay, ...

* Util modules operate on a specific set of `${Type}s` – where `$Type` eq 'Schema', etc. ("Utilities for Strings", not "Utilities for String")
* BuiltIn modules provide a set of pre-built instances of `${Type}s` ("Bool & Int are the built-in Scalars", not "... the Built-in Scalar")

These modules provide a set of things (plural); `Util::*` provides a set of subroutines and `BuiltIn::*` provide a set of pre-built instances. In most other cases a module maps to a class and the singular makes sense (class `==` singular thing, ... that can make many instances). 

In the case of `Graph::QL::Resolvers` it is a class (singular) whose instances hold a collection of `Graph::QL::Resolvers::TypeResolver` instances. So it being a collection, the `Graph::QL::Resolvers` (plural) name is not that offensive, but then as we descend into the sub-namespace, it gets yuckier because we have `::Resolvers` followed by `Resolver`. 

As I type this, I am thinking, ... maybe something like this would be better.

* `Graph::QL::Resolver::SchemaResolver` - Current `Graph::QL::Resolvers`
* `Graph::QL::Resolver::TypeResolver` - no change
* `Graph::QL::Resolver::FieldResolver` - no change

I think this better maps the "type" of resolver to the "type" of schema objects they operate on. 

It gives me the `Graph::QL::Resolver` parent namespace if I need it 🤔 

What do you think?

**Comment by gonzus** [comment]
❤️
